server:
  port: 9191
  error:
    include-message: never
  servlet:
      context-path: /api 

logging:
  level:
    level:
      '[org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping]': DEBUG

management:
  endpoint:
    gateway:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}

spring:
  application:
    name: GATEWAY-SERVICE
    allow-bean-definition-overriding: true

  cloud:
    gateway: 
      # discovery:
      #   locator:
      #     enabled: true
      #     lower-case-service-id: true
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**, /discount/**, /inventories/**, /variations/**
          filters:
            - PrefixPath=/api
            
        - id: ecommerce-product
          uri: http://localhost:8081/
          predicates:
            - Path=/product/**, /category/**, /admin/**, /inventory/**, /brand/**
          filters:
            - PrefixPath=/api
        - id: ecommerce-cart
          uri: http://localhost:8082/
          predicates:
            - Path=/cart/**
          filters:
            - PrefixPath=/api
        - id: ecommerce-order
          uri: http://localhost:8083/
          predicates:
            - Path=/order/**, /stripe/**
          filters:
            - PrefixPath=/api

  main:
    web-application-type: reactive
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: 2905

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: false
        format_sql: true
    show-sql: false

  data:
    redis:
      host: localhost
      port: 6379
    web:
      pageable:
        size-parameter: size
        max-page-size: 100
        one-indexed-parameters: true
        page-parameter: page
      sort:
        sort-parameter: sort

  profiles:
    active: dev

  sql:
    init:
      mode: always
      
jwt:
  base64-secret: hl4gDqBxBgOSDWqBlvwFYQInjYRGAdS4lUT7Nf3Zk1nItoSQ9wSFDPU+kXHKcKUW/UKbpGv9bCsa9S/QsoFRHw==
  access_token-validity-in-seconds: 90000000
  refresh_token-validity-in-seconds: 100000000

upload-file:
  base-uri: file:///C:/my_projects/SPRING_BOOT/upload/
